
<nav class="sidebar">
  <div class="nav-icon" title="Usuário">
    <i data-lucide="user"></i>
  </div>
  <div class="nav-icon" title="Carros carregados">
    <i data-lucide="truck"></i>
  </div>
  <div class="nav-icon" title="Paletes na rota">
    <i data-lucide="map-pin"></i>
  </div>
  <div class="nav-icon" title="Paletes na empresa">
    <i data-lucide="warehouse"></i>
  </div>
</nav>



<section>
    <div class="container-section">
        <div class="sesao resultado">
             <div class="exibir">
                <h2>Registros</h2>
                <h4>Placa - Motorista (?)</h4>
                <p>Conferente - data</p>
            </div>
        </div>
        <div class="sesao btn">
             <form action="">
                <button onclick="abrirModalCarregar()" type="button">Carregar</button>
                <button onclick="abrirModalCarregar()" type="button">Descarregar</button>
             </form>
        </div>
    </div>
</section>

<div id="container-model">
  <h2>Carregar</h2>
  <form action="">
    <div class="form-group">
      <input type="text" id="numero-carrego" placeholder=" " />
      <label for="numero-carrego">Nº Carrego</label>
    </div>
    <div class="form-group">
      <select id="conferente" >
        <option value="" disabled selected>Conferente/Responsavel</option>
        <option value="teste2">Teste 2</option>
        <option value="teste3">Teste 3</option>
        <option value="teste4">Teste 4</option>
      </select>
    </div>
    <div class="form-group">
      <select id="motorista" >
        <option value="" disabled selected>Motorista</option>
        <option value="teste2">Teste 2</option>
        <option value="teste3">Teste 3</option>
        <option value="teste4">Teste 4</option>
      </select>
    </div>
    <div class="form-group">
      <input type="date" id="data" placeholder=" " />
    </div>
    <div class="form-group">
      <input type="number" id="quantidade-paletes" placeholder=" " />
      <label for="quantidade-paletes">Quantidade paletes</label>
    </div>
    <div class="form-group">
        <button >Enviar</button>
        <button style="background-color: #007bff86" onclick="fecharModalCarregar()" type="button">Cancelar</button>
    </div>
  </form>
</div>
