
<nav class="sidebar">
  <div class="nav-icon" title="Usuário">
    <i data-lucide="user"></i>
  </div>
  <div class="nav-icon" title="Carros carregados">
    <i data-lucide="truck"></i>
  </div>
  <div class="nav-icon" title="Paletes na rota">
    <i data-lucide="map-pin"></i>
  </div>
  <div class="nav-icon" title="Paletes na empresa">
    <i data-lucide="warehouse"></i>
  </div>
</nav>



<section>
    <div class="container-section">
        <div class="sesao resultado">
             <div class="exibir">
                <h2>Registros (?)</h2>
                <?php foreach($this->view->paletesUser as $userPaletes) { ?>                 
                  <h4>Nº <?= $userPaletes['carrego'] ?> | Placa: <?= $userPaletes['placa'] ?> | Motorista: <?= $userPaletes['motorista'] ?> (<?= $userPaletes['quantidade'] ?>)</h4>
                  <p>Conferente: <?= $userPaletes['conferente'] ?> - <?= $userPaletes['data'] ?></p> <br>
                <?php } ?>              
            </div>
        </div>
        <div class="sesao btn">
             <form action="">
                <div class="form-group">
                <button onclick="abrirModalCarregar()" type="button">
                    <i data-lucide="upload" class="icon"></i> Carregar
                </button>
                <button onclick="abrirModalCarregar()" type="button" style="background-color: #007bff86">
                    <i data-lucide="download" class="icon"></i> Descarregar
                </button>
                </div>
             </form>
        </div>
    </div>
</section>

<div id="container-model">
  <h2>Carregar</h2>

  <form action="/adicionarPaletes" method="post">
    <div class="form-group">
      <input type="text" name="carregoNumero" placeholder=" " required />
      <label for="numero-carrego">Nº Carrego</label>
    </div>

    <div class="form-group">
      <select name="conferente" required>
        <option value="" disabled selected hidden>Selecione o conferente</option>
        <option value="teste2">Teste 2</option>
        <option value="teste3">Teste 3</option>
        <option value="teste4">Teste 4</option>
      </select>
    </div>

    <div class="form-group">
      <select name="motorista" required>
        <option value="" disabled selected hidden>Selecione o motorista</option>
        <option value="teste2">Teste 2</option>
        <option value="teste3">Teste 3</option>
        <option value="teste4">Teste 4</option>
      </select>
    </div>

    <div class="form-group">
      <input type="text" name="placa" placeholder=" " required />
      <label for="quantidade-paletes">Placa</label>
    </div>

    <div class="form-group">
      <input type="number" name="quantidade" placeholder=" " required />
      <label for="quantidade-paletes">Quantidade paletes</label>
    </div>

    <div class="form-group">
      <button type="submit">Enviar</button>
      <button style="background-color: #007bff86" onclick="fecharModalCarregar()" type="button">Cancelar</button>
    </div>
  </form>

</div>
