<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<script src="https://unpkg.com/lucide@latest/dist/umd/lucide.min.js"></script>
		<link rel="stylesheet" href="css/style.css">
		<title>PalletFlow</title>
	</head>
	<body>
		<?= $this->content() ?>
		<script src="js/index.js"></script>

		<script>
			lucide.createIcons();
		</script>
	</body>
</html>